export const panelCss = `:root{
  color-scheme:dark;
  font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  color:#e7edf7;
  background:#09101b;
  font-synthesis:none
}
*{box-sizing:border-box}
[hidden]{display:none!important}
body{min-width:320px;margin:0;min-height:100vh;background:radial-gradient(circle at top,#172941 0,#0c1624 38rem,#09101b 100%);line-height:1.5}
main{width:min(1180px,100%);margin:auto;padding:2rem 1.5rem 3.5rem}
a{color:#87c5ff;text-decoration-thickness:1px;text-underline-offset:3px}
a:hover{color:#c3e2ff}
.site-header{display:flex;justify-content:space-between;align-items:center;gap:1.25rem;padding:.25rem 0 1.25rem}
.brand-name{margin:0;color:#f7fbff;font-size:1.35rem;font-weight:750;line-height:1.2;letter-spacing:-.025em}
.brand p{margin:.35rem 0 0;color:#9fb0c6;font-size:.9rem}
.logout{display:flex;align-items:center;gap:.75rem}
.module-nav{position:sticky;top:.75rem;z-index:10;margin:0 0 1.25rem;padding:.4rem;background:rgb(15 28 45 / 92%);border:1px solid rgb(150 181 216 / 20%);border-radius:14px;box-shadow:0 12px 34px rgb(0 0 0 / 18%);backdrop-filter:blur(14px)}
.module-nav ul{display:flex;gap:.2rem;list-style:none;margin:0;padding:0;overflow-x:auto;scrollbar-width:none}.module-nav ul::-webkit-scrollbar{display:none}
.module-nav a{display:block;padding:.6rem .8rem;color:#aebed0;border:1px solid transparent;border-radius:9px;font-size:.9rem;font-weight:650;text-decoration:none;white-space:nowrap;transition:background-color .15s,color .15s,border-color .15s}
.module-nav a:hover{color:#e8f3ff;background:#1c3049}
.module-nav a[aria-current="page"]{color:#f4f9ff;background:#214365;border-color:#4075a3;box-shadow:inset 0 1px 0 rgb(255 255 255 / 9%)}
.guild-back{margin:-.35rem 0 1rem;font-size:.9rem;color:#aebed0}
.page-heading{margin:0 0 1.25rem}.page-heading p{margin:0 0 .2rem;color:#9fafc1;font-size:.85rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase}.page-heading h1{margin:0;color:#f6faff;font-size:1.55rem;letter-spacing:-.03em}
.card{margin:1rem 0;padding:1.4rem;background:linear-gradient(145deg,rgb(24 40 60 / 96%),rgb(15 27 43 / 96%));border:1px solid rgb(156 189 224 / 18%);border-radius:15px;box-shadow:0 12px 30px rgb(0 0 0 / 14%)}
.card h1,.card h2{margin:0 0 1rem;color:#f6faff;letter-spacing:-.015em;overflow-wrap:anywhere}.card h1{font-size:1.4rem}.card h2{font-size:1.1rem}.card h1:last-child,.card h2:last-child{margin-bottom:0}
.narrow{max-width:34rem;margin:12vh auto}
form{display:grid;gap:1rem}.card>form{max-width:48rem}.card>form:not(:has(fieldset)){max-width:38rem}.card>form:has(.levels-table){max-width:none}
.game-server-config-group{display:grid;gap:.85rem}.game-server-config-group .hint{margin:0}
.description-toolbar{display:flex;flex-wrap:wrap;gap:.4rem}.description-toolbar button{font-size:.85rem;min-height:2.3rem}
.card-line-editor{display:grid;gap:.65rem;margin-top:.8rem}.card-line-editor .actions select{flex:1 1 15rem;min-width:0;width:100%}.card-line-editor .actions{flex-wrap:wrap}.card-line-editor textarea{min-height:5rem}#card-preview-lines>div{margin:.7rem 0}#card-preview-lines p{white-space:pre-wrap;margin:.2rem 0}#card-preview-lines h1{font-size:1.5rem}#card-preview-lines h2{font-size:1.25rem}#card-preview-lines h3{font-size:1.05rem}#card-preview-lines small{display:block;color:#9fafc1}#card-preview-lines code{white-space:pre-wrap}
fieldset{min-width:0;margin:0;padding:1.15rem;border:1px solid rgb(156 189 224 / 17%);border-radius:11px;background:rgb(8 17 29 / 32%)}
fieldset.card{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem 1.15rem;width:100%;max-width:48rem;margin:0;padding:1.15rem;box-shadow:none}fieldset.card .field{margin:0}legend{padding:0 .45rem;color:#c8d7e7;font-size:.88rem;font-weight:700}
label{display:grid;gap:.4rem;color:#dbe8f5;font-size:.92rem;font-weight:600}.field{margin-bottom:.5rem}.hint{margin:.2rem 0;color:#9fafc1;font-size:.85rem;overflow-wrap:anywhere}
input,select,textarea,button,.button{min-height:2.6rem;font:inherit;color:#edf5fd;background:#0b1624;border:1px solid #3b526c;border-radius:8px;padding:.55rem .7rem}
input,select,textarea{width:100%;box-shadow:inset 0 1px 2px rgb(0 0 0 / 18%)}input:hover,select:hover,textarea:hover{border-color:#5b7898}textarea{min-height:6rem;resize:vertical}select[multiple]{min-height:9rem}
button,.button{display:inline-flex;align-items:center;justify-content:center;width:max-content;background:#245783;border-color:#407aa9;color:#f7fbff;font-weight:700;line-height:1.2;text-decoration:none;cursor:pointer;transition:background-color .15s,border-color .15s,transform .15s}
button:hover,.button:hover{color:#fff;background:#2d689b;border-color:#69a3d3}button:active,.button:active{transform:translateY(1px)}button:disabled,.button.disabled{opacity:.48;cursor:not-allowed;transform:none}
.secondary{background:#1b2b3e;border-color:#486079;color:#d8e6f4}.secondary:hover{background:#29425d;border-color:#6485a5}.danger{background:#4a2530;border-color:#93505f;color:#ffd9df}.danger:hover{background:#69313f;border-color:#bb6c7c;color:#fff}
button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #8ec9ff;outline-offset:3px}input[type="checkbox"]{width:1.05rem;min-height:1.05rem;padding:0;accent-color:#62b3f4}.checkbox{display:flex;align-items:center;gap:.55rem;font-weight:500}.checkbox input{flex:none}
table{width:100%;border-collapse:collapse;font-size:.92rem}.table-wrap{min-width:0;overflow-x:auto;border:1px solid rgb(156 189 224 / 13%);border-radius:10px;background:#0c1725}.table--records{table-layout:fixed}th,td{min-width:0;padding:.8rem .9rem;text-align:left;vertical-align:top;border-bottom:1px solid rgb(156 189 224 / 12%);overflow-wrap:anywhere}th{background:#132338;color:#b8cce0;font-size:.76rem;font-weight:750;letter-spacing:.055em;text-transform:uppercase;white-space:nowrap}tbody tr:last-child td{border-bottom:0}tbody tr:hover{background:rgb(102 165 218 / 7%)}
.audit-table th:nth-child(1){width:8rem}.audit-table th:nth-child(2){width:8.5rem}.audit-table th:nth-child(3){width:7rem}.audit-table th:nth-child(4){width:9rem}.audit-table th:nth-child(5){width:7.5rem}
.levels-table table{min-width:40rem}.levels-table input,.levels-table select{min-width:6rem}.levels-table td:last-child{white-space:nowrap}.level-field-label{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.notice,.error-summary{margin:1rem 0;padding:.85rem 1rem;border:1px solid transparent;border-radius:9px}.notice{background:#103525;border-color:#246c4e;color:#baf4d1}.notice.warning{background:#3b2910;border-color:#855c1a;color:#ffd991}.notice.error,.error-summary{background:#421c26;border-color:#874050;color:#ffd0d7}.error-summary h2{margin:0 0 .45rem;font-size:1rem}.error-summary ul{margin:.35rem 0 0;padding-left:1.25rem}.field-error{display:block;color:#ffb9c4;font-size:.85rem;font-weight:500}
.badge{display:inline-flex;align-items:center;min-height:1.55rem;padding:.18rem .55rem;border:1px solid transparent;border-radius:999px;font-size:.75rem;font-weight:700;line-height:1.2;white-space:nowrap}.badge.production-ready,.badge.enabled,.badge.online{background:#123d2c;border-color:#286b50;color:#a4edc5}.badge.in-development,.badge.disabled,.badge.offline{background:#283648;border-color:#465d76;color:#c0cede}.badge.needs-attention,.badge.degraded{background:#44300e;border-color:#87621b;color:#ffdb8a}.badge.unconfigured,.badge.unavailable{background:#47202a;border-color:#874453;color:#ffc0ca}.ok{color:#a4edc5}.bad,.warning{color:#ffcf82}.empty{margin:0;color:#9fafc1;font-style:italic}
.dl{display:grid;grid-template-columns:minmax(9rem,max-content) minmax(0,1fr);gap:.4rem 1.25rem}.dl dt{color:#9fafc1;font-weight:650}.dl dd{margin:0;overflow-wrap:anywhere}.actions{display:flex;gap:.65rem;align-items:center;flex-wrap:wrap;margin-top:1rem}.actions form{display:contents}.read-only{padding:1rem;background:#101d2d;border:1px solid rgb(156 189 224 / 18%);border-radius:10px}.read-only p{margin:.3rem 0}
.module-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));gap:1rem}.module-card{display:flex;flex-direction:column;align-items:flex-start;min-width:0;min-height:11rem;padding:1.15rem;background:#101f31;border:1px solid rgb(156 189 224 / 18%);border-radius:12px;box-shadow:inset 0 1px 0 rgb(255 255 255 / 3%)}.module-card h3{margin:0 0 .75rem;font-size:1rem;overflow-wrap:anywhere}.module-card h3 a{color:#f0f7ff;text-decoration:none}.module-card h3 a:hover{text-decoration:underline}.module-card p{margin:.25rem 0;overflow-wrap:anywhere}.module-card .actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(8rem,1fr));width:100%;margin-top:auto;padding-top:.85rem}.module-card .actions button,.module-card .actions .button{width:100%}
.server-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.server-card{min-width:0;padding:1.1rem;background:#101f31;border:1px solid rgb(156 189 224 / 18%);border-radius:12px;box-shadow:inset 0 1px 0 rgb(255 255 255 / 3%)}.server-card-header{display:flex;align-items:flex-start;justify-content:space-between;gap:.75rem}.server-card-title{min-width:0}.server-card-eyebrow,.server-card-actions>p{margin:0;color:#9fafc1;font-size:.76rem;font-weight:750;letter-spacing:.055em;text-transform:uppercase}.server-card h3{margin:.15rem 0 0;color:#f2f8ff;font-size:1.08rem;letter-spacing:-.015em;overflow-wrap:anywhere}.server-card-badges{display:flex;gap:.4rem;flex-wrap:wrap;margin:1rem 0 .85rem}.server-card-details{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin:0}.server-card-details div{min-width:0}.server-card-details .server-card-displays{grid-column:1/-1}.server-card-details dt{color:#9fafc1;font-size:.8rem;font-weight:650}.server-card-details dd{margin:.1rem 0 0;overflow-wrap:anywhere}.server-card-actions{margin-top:1rem;padding-top:.9rem;border-top:1px solid rgb(156 189 224 / 14%)}.server-card-actions .actions{margin-top:.6rem}
.filter-nav{display:flex;gap:.35rem;align-items:center;flex-wrap:wrap;margin:0 0 1rem}.filter-nav a{padding:.35rem .7rem;border:1px solid transparent;border-radius:7px;color:#aebed0;font-size:.82rem;font-weight:650;text-decoration:none;text-transform:capitalize}.filter-nav a:hover{background:#1c3049;color:#edf6ff}.filter-nav a[aria-current="true"]{background:#214365;border-color:#4075a3;color:#f4f9ff}.filter-nav form{display:flex;gap:.5rem;align-items:center}.filter-nav select{width:auto}
body:has(form[action$="/edit"]) main{width:min(1800px,100%)}
form[action$="/edit"]{width:100%;max-width:none;min-width:0;display:grid;grid-template-columns:minmax(0,1.65fr) minmax(360px,520px);align-items:start;gap:1rem}
form[action$="/edit"]>.game-server-section-nav,form[action$="/edit"]>#server-settings,form[action$="/edit"]>.notice,form[action$="/edit"]>.game-server-savebar{grid-column:1/-1}
form[action$="/edit"]>.game-server-section-nav{grid-row:1}form[action$="/edit"]>#server-settings{grid-row:2}
form[action$="/edit"]>#card-designer{grid-column:1;grid-row:3;min-width:0}
form[action$="/edit"]>.game-server-preview{grid-column:2;grid-row:3;position:sticky;top:9rem;align-self:start;min-width:0;max-height:none;overflow:visible}
form[action$="/edit"]:has([data-submitted-edits])>.notice{grid-row:1}form[action$="/edit"]:has([data-submitted-edits])>.game-server-section-nav{grid-row:2}form[action$="/edit"]:has([data-submitted-edits])>#server-settings{grid-row:3}form[action$="/edit"]:has([data-submitted-edits])>#card-designer{grid-row:4}form[action$="/edit"]:has([data-submitted-edits])>.game-server-preview{grid-row:4}
.game-server-section-nav{position:sticky;top:4.85rem;z-index:8;display:flex;gap:.35rem;overflow-x:auto;padding:.45rem;background:rgb(15 28 45 / 96%);border:1px solid rgb(150 181 216 / 20%);border-radius:11px;scrollbar-width:thin}
.game-server-section-nav a{flex:none;padding:.62rem .82rem;border:1px solid transparent;border-radius:7px;color:#b8cce0;font-size:.84rem;font-weight:700;text-decoration:none;white-space:nowrap}.game-server-section-nav a:hover,.game-server-section-nav a:focus-visible,.game-server-section-nav a[aria-current="location"]{background:#214365;border-color:#4075a3;color:#fff}
.game-server-section-nav a:focus-visible{outline:3px solid #8ec9ff;outline-offset:2px}
.game-server-preview{min-width:0;max-width:100%}.game-server-preview #card-preview-lines{min-width:0;max-width:100%;margin-top:.8rem;padding:.85rem;border-radius:9px;background:#0b1420;overflow-wrap:anywhere}.game-server-preview #card-preview-lines *, .game-server-preview #card-preview-artwork, .game-server-preview #card-preview-artwork *, .game-server-preview #card-preview-actions, .game-server-preview #card-preview-actions *{min-width:0;max-width:100%;overflow-wrap:anywhere;word-break:break-word}.game-server-preview #card-preview-lines>div{margin:.65rem 0}.game-server-preview hr{margin:.85rem 0;border:0;border-top:1px solid #35495f}.preview-artwork{display:grid;place-items:center;min-height:5rem;padding:.8rem;border:1px dashed #54708d;border-radius:8px;background:linear-gradient(135deg,#182b40,#0d1928);color:#bdcfe2;text-align:center}.preview-action-row{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.7rem}.preview-action{display:inline-flex;align-items:center;justify-content:center;min-height:2.4rem;padding:.45rem .75rem;border:1px solid #407aa9;border-radius:8px;background:#245783;color:#f7fbff;font-weight:700}
.card-line-editor{display:block;min-width:0;margin:.55rem 0;padding:0;overflow:hidden}.card-line-editor>summary{display:grid;grid-template-columns:minmax(7rem,auto) minmax(0,1fr) auto;gap:.25rem .8rem;align-items:center;padding:.7rem .8rem;color:#e8f1fc;cursor:pointer;list-style:none}.card-line-editor>summary::-webkit-details-marker{display:none}.card-line-editor>summary:before{content:"+";grid-column:3;grid-row:1;font-size:1.15rem;color:#8ec9ff}.card-line-editor[open]>summary:before{content:"−"}.line-summary-title{font-weight:750}.line-summary-text{min-width:0;overflow:hidden;color:#aebed0;text-overflow:ellipsis;white-space:nowrap}.line-summary-meta{grid-column:2;color:#87c5ff;font-size:.78rem}.card-line-content{display:grid;gap:.75rem;padding:0 .85rem .9rem}.card-line-content>.actions{margin-top:.2rem}.inline-help{display:inline-block;margin-left:.35rem}.inline-help summary{display:inline;color:#87c5ff;cursor:pointer;font-weight:650}.inline-help p{max-width:55rem;margin:.55rem 0 0;padding:.7rem;border-left:2px solid #4f91c1;background:#101d2d}
.game-server-advanced{margin-top:.5rem;border-top:1px solid rgb(156 189 224 / 17%);padding-top:.65rem}.game-server-advanced>summary{color:#b8cce0;font-weight:700;cursor:pointer}
.game-server-savebar{position:static;z-index:1;display:flex;align-items:center;justify-content:flex-end;gap:.6rem;flex-wrap:wrap;padding:.65rem .8rem;background:rgb(15 28 45 / 96%);border:1px solid rgb(150 181 216 / 25%);border-radius:12px;box-shadow:0 8px 30px rgb(0 0 0 / 20%)}.game-server-savebar .hint{margin:0 auto 0 0}.game-server-savebar button{min-height:2.5rem}
form[action$="/edit"] :target{scroll-margin-top:9rem}
@media(max-width:1100px){.audit-table .table-wrap{overflow:visible;border:0;background:transparent}.audit-table .table--records,.audit-table .table--records tbody,.audit-table .table--records tr,.audit-table .table--records td{display:block}.audit-table .table--records thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.audit-table .table--records tbody{display:grid;gap:.8rem}.audit-table .table--records tr{padding:.85rem;border:1px solid rgb(156 189 224 / 18%);border-radius:10px;background:#0c1725}.audit-table .table--records td{display:grid;grid-template-columns:minmax(7.25rem,42%) minmax(0,1fr);gap:.75rem;padding:.45rem 0;border:0}.audit-table .table--records td+td{border-top:1px solid rgb(156 189 224 / 12%)}.audit-table .table--records td::before{content:attr(data-label);color:#9fafc1;font-size:.72rem;font-weight:750;letter-spacing:.055em;text-transform:uppercase}}
@media(max-width:1050px){form[action$="/edit"]{grid-template-columns:minmax(0,1fr) minmax(270px,340px)}}
@media(max-width:800px){form[action$="/edit"]{grid-template-columns:minmax(0,1fr)}form[action$="/edit"]>#card-designer,form[action$="/edit"]>.game-server-preview{grid-column:1;grid-row:auto}form[action$="/edit"]>.game-server-preview{position:static;max-height:none;order:4}.game-server-section-nav{top:4.2rem}}
@media(max-width:520px){.card-line-editor>summary{grid-template-columns:minmax(0,1fr) auto;gap:.15rem .5rem}.card-line-editor>summary:before{grid-column:2;grid-row:1}.line-summary-text,.line-summary-meta{grid-column:1/-1}.game-server-savebar{bottom:.25rem;gap:.4rem}.game-server-savebar .hint{flex:1 0 100%}.game-server-savebar button{flex:1;min-width:0;padding-inline:.45rem;font-size:.82rem}}
@media(max-height:700px){form[action$="/edit"]>.game-server-preview{position:static}}
@media(max-width:650px){main{padding:1.1rem 1rem 2.5rem}.site-header{align-items:flex-start;flex-direction:column;padding-bottom:1rem}.logout{width:100%}.logout button{width:100%}.module-nav{top:.35rem;margin-left:-.25rem;margin-right:-.25rem;border-radius:11px}.module-nav:after{content:"";position:absolute;top:.4rem;right:.4rem;bottom:.4rem;width:1.5rem;border-radius:0 8px 8px 0;background:linear-gradient(90deg,transparent,#0f1c2d);pointer-events:none}.module-nav a{padding:.58rem .7rem}.page-heading h1{font-size:1.35rem}.card{padding:1.1rem;border-radius:12px}.card>form,fieldset.card{max-width:none}fieldset.card{grid-template-columns:1fr}.actions{align-items:stretch;flex-direction:column}.actions button,.actions .button{width:100%}.dl{grid-template-columns:1fr;gap:.2rem}.dl dd{margin-bottom:.6rem}.filter-nav form{align-items:stretch;flex-direction:column}.filter-nav select{width:100%}.module-grid,.server-grid{grid-template-columns:1fr}.module-card{min-height:0}.module-card .actions{display:flex}.server-card-details{grid-template-columns:1fr}.server-card-details .server-card-displays{grid-column:auto}
.table-wrap:has(.table--records){overflow:visible;border:0;background:transparent}.table--records,.table--records tbody,.table--records tr,.table--records td{display:block}.table--records thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.table--records tbody{display:grid;gap:.8rem}.table--records tr{padding:.85rem;border:1px solid rgb(156 189 224 / 18%);border-radius:10px;background:#0c1725}.table--records td{display:grid;grid-template-columns:minmax(7.25rem,42%) minmax(0,1fr);gap:.75rem;padding:.45rem 0;border:0}.table--records td+td{border-top:1px solid rgb(156 189 224 / 12%)}.table--records td::before{content:attr(data-label);color:#9fafc1;font-size:.72rem;font-weight:750;letter-spacing:.055em;text-transform:uppercase}.table--records td[data-label=""]{display:flex;justify-content:flex-end}.table--records td[data-label=""]::before{display:none}}
@media(max-width:760px){.levels-table{overflow:visible;border:0;background:transparent}.levels-table table{display:block;min-width:0}.levels-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.levels-table tbody{display:grid;gap:.8rem}.levels-table tr{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem;padding:.85rem;border:1px solid rgb(156 189 224 / 18%);border-radius:10px;background:#0c1725}.levels-table td{display:block;min-width:0;padding:0;border:0}.levels-table td:nth-child(n+3){grid-column:1/-1}.levels-table td:last-child{white-space:normal}.levels-table td:last-child button{width:100%}.levels-table input,.levels-table select{min-width:0}.level-field-label{position:static;width:auto;height:auto;overflow:visible;clip-path:none;white-space:normal}}
@media(min-width:380px) and (max-width:650px){.server-card-details{grid-template-columns:repeat(2,minmax(0,1fr))}.server-card-details .server-card-displays{grid-column:1/-1}}
@media(max-width:399px){.table--records td,.audit-table .table--records td{grid-template-columns:1fr;gap:.2rem}.table--records td[data-label=""]{align-items:stretch}.table--records td[data-label=""] button,.table--records td[data-label=""] .button{width:100%}}
.layout-add-menu>summary{cursor:pointer;width:max-content;padding:.55rem .8rem;border:1px solid #486079;border-radius:8px;background:#1b2b3e;font-weight:700}.layout-add-menu[open] .layout-add-actions{padding-top:.65rem}.game-server-preview[data-tall="true"]{position:static!important}@media(max-width:900px){.game-server-savebar{position:static}}
.saved-layout-json{white-space:pre-wrap;overflow-wrap:anywhere;max-width:100%;padding:1rem;font-size:.85rem;background:#0b1725}.card-settings-group h3{padding:0 1rem}
.layout-row-menu{position:relative}.layout-row-menu>summary{cursor:pointer;color:#cbdced;min-width:2rem;min-height:2.2rem;padding:.3rem;text-align:center;border:1px solid #486079;border-radius:7px;list-style:none}.layout-row-menu[open]>div{position:absolute;right:0;top:2.5rem;z-index:5;display:grid;gap:.35rem;padding:.5rem;border:1px solid #486079;border-radius:8px;background:#0b1725;box-shadow:0 6px 20px #0008}.layout-row-menu[open]>div button{width:100%;min-width:6.5rem}.preview-thumbnail-frame{margin:0;flex:0 0 80px;max-width:80px!important}.preview-thumbnail-frame .preview-artwork{font-size:.7rem;min-height:80px;padding:.3rem}.preview-card-disclosure>summary{cursor:pointer;font-size:.85rem;color:#c8d7e7;margin-top:.7rem}.preview-section>div{min-width:0}.preview-updates .preview-action{flex:none;align-self:center}.card-layout-row .card-layout-content{display:none}
/* Game server card workspace: structure, contextual properties, and Discord preview. */
body:has(#card-layout-workspace) main{width:min(1880px,100%)}
form:has(#card-layout-workspace){grid-template-columns:minmax(0,1fr) minmax(380px,540px)}
#server-settings{grid-template-columns:repeat(3,minmax(0,1fr));align-items:start}
#server-settings .hint{font-size:.85rem}#server-settings label{max-width:28rem}
#card-designer{padding:1rem;gap:1rem}#card-text-settings{padding:.85rem;background:#101c2b}
#card-layout-workspace{display:grid;grid-template-columns:minmax(220px,.8fr) minmax(0,1.2fr);gap:1rem;align-items:start}
#card-layout-list,#card-layout-properties{min-width:0}#card-layout-properties,.game-server-preview{scroll-margin-top:9rem}#card-layout-list h3{margin:.15rem 0 .25rem;font-size:1rem}
#card-layout-editors{display:grid;gap:.45rem;margin-top:.75rem}
.card-layout-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.35rem;padding:.45rem;border:1px solid #35495f;border-radius:9px;background:#142235;min-width:0}
.card-layout-row.is-selected{border-color:#86c6fb;background:#1c3853;box-shadow:inset 3px 0 #86c6fb}
.card-layout-row-main{display:flex;gap:.6rem;align-items:flex-start;text-align:left;min-width:0;width:100%;padding:.3rem;background:transparent;border-color:transparent;font-weight:500}
.card-layout-row-main:hover{background:#223b53}.card-layout-row-icon{flex:none;width:1.2rem;color:#91caff;font-size:1.1rem}
.card-layout-row-copy{display:grid;gap:.2rem;min-width:0}.card-layout-row-copy strong{font-size:.92rem;line-height:1.3;overflow-wrap:anywhere}
.card-layout-row-summary{display:block;font-size:.8rem;line-height:1.4;font-weight:400;color:#b5c6d9;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:100%}
.card-layout-row-actions{display:flex;gap:.2rem;align-items:center}.card-layout-row-actions button{min-height:2.2rem;padding:.3rem .45rem;background:transparent;border-color:#486079}
.card-layout-row .card-layout-content{display:none}#card-layout-properties{padding:1rem;border:1px solid #415872;border-radius:10px;background:#0b1725}
#card-layout-properties .card-layout-content{display:grid;gap:.8rem}#card-layout-properties textarea{min-height:9rem}
.card-layout-property-header{margin-bottom:.8rem}.card-layout-property-header h3{margin:0 0 .3rem;font-size:1.1rem}
.card-layout-property-actions{display:flex;gap:.4rem;flex-wrap:wrap;padding-top:.8rem;border-top:1px solid #35495f}
.card-layout-property-actions button{font-size:.85rem;min-height:2.4rem}#card-layout-properties .actions{gap:.4rem;margin:0}
#card-layout-properties fieldset{padding:.8rem;background:#142235}.card-layout-properties-empty{color:#b5c6d9;margin:0}
.updates-feed-order[hidden],[data-updates-separator-settings]{display:none!important}
.updates-block-builder{min-width:0}.updates-block-builder [data-updates-blocks]{display:grid;gap:.55rem;margin:.6rem 0}
.updates-block-row{display:grid;gap:.55rem;padding:.7rem;background:#0d1b2b;border:1px solid #35495f;border-radius:8px;min-width:0}
.updates-block-row-header{display:flex;align-items:center;flex-wrap:wrap;gap:.65rem}
.updates-block-row-header strong{flex:1;min-width:6rem;overflow-wrap:anywhere}
.updates-block-row-header .checkbox{margin:0;max-width:none}
.updates-block-row-actions{display:flex;flex-wrap:wrap;gap:.3rem}
.updates-block-row-actions button{padding:.35rem .55rem;min-height:2.2rem}
.updates-block-config{min-width:0;display:grid;gap:.55rem}
.updates-block-config textarea{min-height:5rem!important}
.updates-block-config [data-gallery-items]{display:grid;gap:.6rem}
.updates-block-config fieldset{min-width:0;display:grid;gap:.55rem}
@media(max-width:600px){.updates-block-row-header{align-items:flex-start}.updates-block-row-actions{width:100%}}
.updates-feed-order{display:grid;gap:.45rem}.updates-feed-order-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:.6rem;padding:.45rem .55rem;border:1px solid #35495f;border-radius:8px;background:#0d1b2b}.updates-feed-order-row>strong{overflow-wrap:anywhere}.updates-feed-order-row>div{display:flex;gap:.25rem}.updates-feed-order-row button{min-width:2.3rem;min-height:2.3rem;padding:.3rem}.updates-feed-separator{display:grid;grid-template-columns:auto auto minmax(0,1fr);align-items:center;gap:.45rem;padding:.25rem .55rem;color:#b8cce0;font-size:.85rem}.updates-feed-separator>span:last-child{color:#8fa5bc}.updates-feed-settings{border-top:1px solid #35495f;padding-top:.55rem}.updates-feed-settings>summary,.updates-advanced>summary{cursor:pointer;color:#cbdced;font-weight:650}.updates-feed-settings>.card-layout-content,.updates-advanced>.card-layout-content{display:grid;gap:.7rem;padding:.65rem 0}.updates-advanced{margin-top:.4rem}.preview-update-heading{margin:.25rem 0 .5rem}.preview-updates{gap:.65rem}.preview-updates>div{display:grid;gap:.35rem;min-width:0}.preview-text-display.preview-updates{display:block}.preview-update-title{margin:.45rem 0 .1rem!important}.preview-update-summary{margin:.1rem 0 .55rem!important}.preview-updates .preview-action{align-self:center;white-space:nowrap}
.layout-add-actions{display:flex;gap:.4rem;flex-wrap:wrap}.layout-add-actions button{font-size:.85rem;min-height:2.4rem;padding:.45rem .6rem}
.card-layout-undo{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center;margin-top:.75rem;color:#cbdced;font-size:.85rem}
.card-settings-group{border:1px solid #35495f;border-radius:9px;background:#101c2b;min-width:0}.card-settings-group>summary{padding:.8rem 1rem;cursor:pointer;font-weight:700;color:#dceafa}.card-settings-group>summary:focus-visible,details>summary:focus-visible{outline:3px solid #8ec9ff;outline-offset:2px}
.card-settings-content{padding:0 1rem 1rem;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.85rem;align-items:start}.card-settings-content .hint{grid-column:1/-1}
.card-default-actions{display:flex;gap:.7rem;align-items:center;flex-wrap:wrap}.card-default-actions button{font-size:.85rem}
.preview-heading{display:flex;align-items:center;justify-content:space-between;gap:.6rem;margin-bottom:.6rem}.preview-heading h2{margin:0}.preview-heading button{font-size:.82rem;min-height:2.3rem}
.game-server-preview{padding:1rem}.game-server-preview #card-preview-lines{background:#2b2d31;border:1px solid #43464d;border-left:4px solid #2b8aef;padding:1rem;border-radius:8px;color:#f2f3f5}
.preview-section{display:flex;gap:1rem;align-items:flex-start}.preview-section>div{flex:1}.preview-thumbnail{width:80px;height:80px;object-fit:contain;border-radius:8px;flex:none}
.preview-media-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.35rem}.preview-media-gallery:has(>.preview-media-item:only-child){grid-template-columns:minmax(0,1fr)}
.preview-media-item{margin:0;min-width:0;overflow:hidden;border-radius:7px}.preview-media-item img{display:block;width:100%;height:auto;object-fit:contain}.preview-media-item figcaption{font-size:.78rem;color:#c8ced8;padding:.3rem}
.preview-separator-space{height:.7rem}.preview-separator-large{margin-block:1.5rem!important}.preview-action.secondary{background:#4e5058;border-color:#6d7078}
.game-server-preview.is-expanded{grid-column:1/-1!important;grid-row:auto!important;position:static!important;width:100%;max-width:900px;justify-self:center}
.live-state-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.75rem;margin:.9rem 0 1.1rem}.live-state-summary>div{padding:.8rem;background:#142235;border:1px solid #35495f;border-radius:9px}.live-state-summary span{display:block;color:#aebed0;font-size:.8rem}.live-state-summary strong{display:block;margin-top:.2rem;overflow-wrap:anywhere;font-size:1rem}
.read-only>.card-settings-group .dl,.card>.card-settings-group .dl{padding:0 1rem 1rem}
@media(min-width:1550px){#card-layout-workspace{grid-template-columns:minmax(245px,.7fr) minmax(0,1.3fr)}}
@media(max-width:1390px){#card-layout-workspace{grid-template-columns:minmax(0,1fr)}#card-layout-editors{grid-template-columns:repeat(2,minmax(0,1fr))}.card-layout-row{grid-template-columns:minmax(0,1fr)}.card-layout-row-actions{justify-content:flex-end}}
@media(max-width:1120px){form:has(#card-layout-workspace){grid-template-columns:minmax(0,1fr)}form:has(#card-layout-workspace)>#card-designer,form:has(#card-layout-workspace)>.game-server-preview{grid-column:1;grid-row:auto;position:static}#card-layout-workspace{grid-template-columns:minmax(230px,.8fr) minmax(0,1.2fr)}#card-layout-editors{grid-template-columns:1fr}.card-layout-row{grid-template-columns:minmax(0,1fr) auto}.game-server-preview{width:100%;max-width:760px;justify-self:center}.game-server-section-nav{position:static}#server-settings{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:760px){#card-layout-workspace{grid-template-columns:minmax(0,1fr)}#card-layout-editors{grid-template-columns:repeat(2,minmax(0,1fr))}.card-layout-row{grid-template-columns:minmax(0,1fr)}.card-settings-content{grid-template-columns:1fr}.game-server-savebar{position:static}#server-settings{grid-template-columns:1fr}}
@media(max-width:520px){#card-layout-editors{grid-template-columns:1fr}.card-layout-row{grid-template-columns:minmax(0,1fr) auto}#card-designer,#card-text-settings,#card-layout-properties{padding:.7rem}.card-layout-property-actions{flex-direction:row}.card-layout-property-actions button{width:auto}.preview-heading{align-items:flex-start}.preview-heading h2{font-size:1rem}.preview-heading button{max-width:9rem}.preview-thumbnail{width:64px;height:64px}.layout-add-actions button{flex:1 1 9rem}.game-server-preview{padding:.75rem}.game-server-savebar button{font-size:.9rem}}

`;
